version: '3.9'

services:
  lazy-docker:
    image: lazyteam/lazydocker
    container_name: lazy-docker
    ports:
      - ${HOST_PORT}:8080
    env_file:
      - .env
    build:
      args:
        BASE_IMAGE_BUILDER: golang
        GOARCH: amd64
        GOARM:
    stdin_open: true
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/.config/jesseduffield/lazydocker
    