version: '3.9'

services:
  elasticsearch:
    image: xiting/elasticsearch-bitbucket-pipeline
    environment:
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carcolor