version: '3.9'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1-amd64
    environment:
      - discovery.type=single-node
      - logger.level=INFO
      - xpack.security.enabled=false
    ports:
      - 9250:9200